name: update DAGs airflow

on:
    push:
        branches:
          - devops 

jobs:
  update-dags:
    runs-on: ubuntu-latest
# оголошуємо всі змінні 
    env:
        #глобальні змінні організації
        SERVER_IP: ${{secrets.SERVER_IP}}
        SERVER_USER: ${{secrets.SERVER_USER}}
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        DECRYPT_PRIVAT_KEY: ${{secrets.DECRYPT_PRIVAT_KEY}}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files via SCP
      run: |
        echo "${{secrets.SSH_PRIVATE_KEY}}" > key.pem
        echo "${{secrets.DECRYPT_PRIVAT_KEY}}" > privat_key.pem
        chmod 600 key.pem
        mkdir -p $HOME/.ssh && ssh-keyscan -H $SERVER_IP >> $HOME/.ssh/known_hosts
        mkdir decrypted_files
        for file in encrypted_files/*.enc; do
          base=$(basename $file .enc)
          openssl rsautl -decrypt -inkey private_key.pem -in $file -out decrypted_files/$base
        done
        rsync -rav -e "ssh -i key.pem" --delete-after ./ $SERVER_USER@$SERVER_IP:/root/devops
    
      
  
        