name: update DAGs airflow

on:
    push:
        branches:
          - main

jobs:
  update-dags:
    runs-on: ubuntu-latest
# оголошуємо всі змінні 
    env:
        #глобальні змінні організації
        SERVER_IP: ${{secrets.SERVER_IP}}
        SERVER_USER: ${{secrets.SERVER_USER}}
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files via SCP
      run: |
        echo "${{secrets.SSH_PRIVATE_KEY}}" > key.pem
        chmod 600 key.pem
        mkdir -p $HOME/.ssh && ssh-keyscan -H $SERVER_IP >> $HOME/.ssh/known_hosts
        rsync -rav -e "ssh -i key.pem" --delete-after ./ $SERVER_USER@$SERVER_IP:/root/airflow-docker/dags
    
      
  
        